version: '3.8'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: postgres:14
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend/src/main/resources/schema.sql:/tmp/schema.sql:ro
      - ./backend/src/main/resources/data.sql:/tmp/data.sql:ro
    entrypoint: ["/bin/sh","-c"]
    command: >
      "until pg_isready -h db -p 5432; do sleep 1; done;
       export PGPASSWORD=${DB_PASSWORD};
       if [ -f /tmp/schema.sql ]; then psql -h db -U ${DB_USERNAME} -d ${DB_NAME} -f /tmp/schema.sql || true; fi;
       if [ -f /tmp/data.sql ]; then psql -h db -U ${DB_USERNAME} -d ${DB_NAME} -f /tmp/data.sql || true; fi;
       echo 'db-init done';"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8080"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data:
