name: CI/CD - Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend CI
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  
          java-package: jdk
          check-latest: false

      - name: Install Maven Dependencies (Backend)
        run: mvn install -f ./backend/pom.xml

      - name: Build Backend (Maven)
        run: mvn clean package -f ./backend/pom.xml

      - name: Run Backend Tests
        run: mvn test -f ./backend/pom.xml

  # Backend CD
  backend-cd:
    runs-on: ubuntu-latest
    needs: backend-ci
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  
          java-package: jdk
          check-latest: false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Docker Image
      - name: Build Backend Docker Image
        run: docker build -t xdn73/backend:v3 -t xdn73/backend:${{ github.sha }} ./backend

      # Push Backend Docker Image to Docker Hub
      - name: Push Backend Docker Image to Docker Hub
        run: |
          docker push xdn73/backend:latest
          docker push xdn73/backend:${{ github.sha }}

      # Deploy Backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: g5-backend-app
          images: xdn73/backend:v3
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        env:
          DB_HOST: ${{ secrets.AZURE_DB_HOST }}
          DB_PORT: ${{ secrets.AZURE_DB_PORT }}
          DB_NAME: ${{ secrets.AZURE_DB_NAME }}
          DB_USERNAME: ${{ secrets.AZURE_DB_USER }}
          DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          SPRING_PROFILES_ACTIVE: azure

          