name: CI/CD for Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd-backend:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@v4

     
      - name: Set up JDK 17 for Backend
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: jdk
          check-latest: false

     
      - name: Install Backend Dependencies
        run: mvn install -f ./backend/pom.xml

      
      - name: Build Backend
        run: mvn clean package -f ./backend/pom.xml

     
      - name: Run Backend Tests
        run: mvn test -f ./backend/pom.xml

    
      - name: Login to Docker Hub for Backend
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #
      - name: Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME}}/backend:v3 ./backend
          docker push xdn73/backend:v3

     
